CREATE TABLE EGG(EGG_ID INT PRIMARY KEY, CHN_ID INT)
CREATE TABLE CHICKEN(CHN_ID INT PRIMARY KEY,EGG_ID INT REFERENCES EGG(EGG_ID))
ALTER TABLE EGG ADD FOREIGN KEY (CHN_ID) REFERENCES CHICKEN(CHN_ID)

INSERT INTO EGG VALUES (11,NULL)
INSERT INTO EGG VALUES (22,NULL)
INSERT INTO EGG VALUES (33,NULL)

INSERT INTO CHICKEN VALUES(111,11)
INSERT INTO CHICKEN VALUES(222,22)
INSERT INTO CHICKEN VALUES(333,33)

UPDATE EGG SET CHN_ID=111 WHERE EGG_ID=11
UPDATE EGG SET CHN_ID=222 WHERE EGG_ID=22
UPDATE EGG SET CHN_ID=333 WHERE EGG_ID=33

SELECT * FROM EGG
SELECT *  FROM CHICKEN
create table egg(egg_id int primary key,chn_id int)
create table (chn_id int primary key,egg_id int references egg(egg_id))
alter table egg add foreign key(ch-id) references check(chn_id)

insert into egg values (11,null)





